tasks:
  - init: sudo apt install build-essential libnss3 libsecret-1-dev python rsync -y &&
          sudo apt-get update -y &&
          sudo apt-get install libgbm-dev -y &&
          yarn install 
image:
  file: Dockerfile
ports:
  - port: 6080